using FluentAssertions;
using NUnit.Framework;
using Shoebox.Api.Share;

namespace Shoebox.Api.UnitTests.Share
{
    // One format, two implementations: diagram-url.ts encodes in the browser as the user types,
    // ShareLink.cs encodes on the server for callers that cannot compress. Nothing else pins them
    // together.
    //
    // Deliberately NOT a byte-equality test against the TypeScript output. Deflate implementations
    // and levels differ, so two encoders can emit different bytes that both inflate correctly, and
    // a golden-string comparison would fail for a non-bug. What is stable, and what actually
    // matters, is that each side can READ what the other writes.
    [TestFixture]
    public class BrowserVectorTests
    {
        // Captured 2026-08-30 from a link the deployed SPA put in a real browser's address bar --
        // CompressionStream('deflate-raw') then base64url, not generated by anything in this repo.
        private const string BrowserProduced =
            "nZXNTuMwEIDvfopRJCQ4hEdYyQMEpKRa1LLdQ8rBTaepRbArx6HqPv3KdhzSAt0tp2j-Z_yNnXWjd9VGGAvFlAFcXMBsIwytwFCrO1NRywDablkbsd30tjI59kmeGQDAzbRMbrSyQioyMKVattbseyPPbsuE_-kMQWa0snCrtYm2PJtEY94tySiy1ELWEFmYCCVqiq4FL5NC18CVaPZWVqE2qRUL7buqWgEftz3lZRL1fZqVNFRZpymmrE98nHmhLo2PEs1V8hy8hpwPv5CXyUO3BEV2p80LHDgDfKgSVC4qDIqidabBOfs9mDJpaCeaprf1041BPP7M73iZzLb6heBNGtuJJnZyqjzPZ7xMRmfcknmT7wgBCvTnIFaAohGqGk4egD_euxa320ZWwue9F5Z2Yn_cZz53RWgPc9E1dtgOx-HjfiyUIZ_xc5J4QBIHkniCJJ5JEr9FEr8mieeRxO-RxH-RxBMk8T9J4qck8RyS4R5XTddaMmOcWXF393R6du8yKZOJrIxu9dqmr_49WC3UJ7Mv1GUotumWseDVUTdPRqzXsoJ1o3fMv0uQpj_8ch-K2Afw7RaM7qxUNeyk3UgFYUHc2-jCfECB4etuWNBjr8eojwndrlkNrR-70ko5tm_S7pl_BSBN05gmigWOJd-rlzE640gscCzFSTDEuofLSRglHN03RxF6iG4tmIPt23e390BCFq70eGinPh52RpUh644qnx-MNojh4PP5wSyD-M4hkA34X0lZFn4cvmBYExb3BdLr3rGF6_f-vjTGEoWua6lqFh7KwI_zIPY4ueuu4NHohWhifwE";

        [Test]
        public void ReadsALinkTheBrowserWrote()
        {
            var diagram = ShareLink.Decode(BrowserProduced);

            diagram.Should().StartWith("flowchart LR");
            diagram.Should().Contain("subgraph Shared[\"Shared resources\"]");
            diagram.Should().Contain("FLEETM -. manages .-> AKSA",
                "the dotted arrow is one of the forms the parser only learned recently");
            diagram.Should().Contain("APGA --> LBA --> AKSA", "and chains are another");
        }

        [Test]
        public void ReencodesWhatTheBrowserWroteIntoSomethingItCanReadBack()
        {
            // Round trip THROUGH the browser's payload: decode theirs, encode ours, decode ours.
            // Byte-identical output is not required and not asserted; agreement on meaning is.
            var fromBrowser = ShareLink.Decode(BrowserProduced);

            ShareLink.Decode(ShareLink.Encode(fromBrowser)).Should().Be(fromBrowser);
        }
    }
}
